'use client';

import dynamic from 'next/dynamic';
import React from 'react';

const toolComponents: Record<string, React.ComponentType<{ children?: React.ReactNode }>> = {
  crop: dynamic(() => import('@/app/components/tools/CropTool'), { ssr: false }) as any,
  compress: dynamic(() => import('@/app/components/tools/CompressTool'), { ssr: false }) as any,
  resize: dynamic(() => import('@/app/components/tools/ResizeTool'), { ssr: false }) as any,
  rotate: dynamic(() => import('@/app/components/tools/RotateTool'), { ssr: false }) as any,
  brightness: dynamic(() => import('@/app/components/tools/BrightnessTool'), { ssr: false }) as any,
  contrast: dynamic(() => import('@/app/components/tools/ContrastTool'), { ssr: false }) as any,
  saturation: dynamic(() => import('@/app/components/tools/SaturationTool'), { ssr: false }) as any,
  hue: dynamic(() => import('@/app/components/tools/HueTool'), { ssr: false }) as any,
  grayscale: dynamic(() => import('@/app/components/tools/GrayscaleTool'), { ssr: false }) as any,
  blur: dynamic(() => import('@/app/components/tools/BlurTool'), { ssr: false }) as any,
  vintage: dynamic(() => import('@/app/components/tools/VintageTool'), { ssr: false }) as any,
  sharpen: dynamic(() => import('@/app/components/tools/SharpenTool'), { ssr: false }) as any,
  mosaic: dynamic(() => import('@/app/components/tools/MosaicTool'), { ssr: false }) as any,
  rounded: dynamic(() => import('@/app/components/tools/RoundedTool'), { ssr: false }) as any,
  watermark: dynamic(() => import('@/app/components/tools/WatermarkTool'), { ssr: false }) as any,
  grid: dynamic(() => import('@/app/components/tools/GridTool'), { ssr: false }) as any,
  colorExtract: dynamic(() => import('@/app/components/tools/ColorExtractTool'), { ssr: false }) as any,
  eyedropper: dynamic(() => import('@/app/components/tools/EyedropperTool'), { ssr: false }) as any,
  exif: dynamic(() => import('@/app/components/tools/ExifTool'), { ssr: false }) as any,
  base64: dynamic(() => import('@/app/components/tools/Base64ImageTool'), { ssr: false }) as any,
  formatConvert: dynamic(() => import('@/app/components/tools/FormatConvertTool'), { ssr: false }) as any,
  compare: dynamic(() => import('@/app/components/tools/CompareTool'), { ssr: false }) as any,
  toPdf: dynamic(() => import('@/app/components/tools/ToPdfTool'), { ssr: false }) as any,
  bgRemove: dynamic(() => import('@/app/components/tools/BgRemoveTool'), { ssr: false }) as any,
  zip: dynamic(() => import('@/app/components/tools/ZipTool'), { ssr: false }) as any,
  unzip: dynamic(() => import('@/app/components/tools/UnzipTool'), { ssr: false }) as any,
  preview: dynamic(() => import('@/app/components/tools/PreviewTool'), { ssr: false }) as any,
  fileHash: dynamic(() => import('@/app/components/tools/FileHashTool'), { ssr: false }) as any,
  editor: dynamic(() => import('@/app/components/tools/EditorTool'), { ssr: false }) as any,
  wordCount: dynamic(() => import('@/app/components/tools/WordCountTool'), { ssr: false }) as any,
  textClean: dynamic(() => import('@/app/components/tools/TextCleanTool'), { ssr: false }) as any,
  caseConvert: dynamic(() => import('@/app/components/tools/CaseConvertTool'), { ssr: false }) as any,
  textReverse: dynamic(() => import('@/app/components/tools/TextReverseTool'), { ssr: false }) as any,
  markdownToHtml: dynamic(() => import('@/app/components/tools/MarkdownToHtmlTool'), { ssr: false }) as any,
  markdown: dynamic(() => import('@/app/components/tools/MarkdownTool'), { ssr: false }) as any,
  whitespace: dynamic(() => import('@/app/components/tools/WhitespaceTool'), { ssr: false }) as any,
  dedup: dynamic(() => import('@/app/components/tools/DedupTool'), { ssr: false }) as any,
  extractInfo: dynamic(() => import('@/app/components/tools/ExtractInfoTool'), { ssr: false }) as any,
  lineSort: dynamic(() => import('@/app/components/tools/LineSortTool'), { ssr: false }) as any,
  traditionalSimplified: dynamic(() => import('@/app/components/tools/TraditionalSimplifiedTool'), { ssr: false }) as any,
  escape: dynamic(() => import('@/app/components/tools/EscapeTool'), { ssr: false }) as any,
  lineNumber: dynamic(() => import('@/app/components/tools/LineNumberTool'), { ssr: false }) as any,
  trimText: dynamic(() => import('@/app/components/tools/TrimTextTool'), { ssr: false }) as any,
  mergeLines: dynamic(() => import('@/app/components/tools/MergeLinesTool'), { ssr: false }) as any,
  splitText: dynamic(() => import('@/app/components/tools/SplitTextTool'), { ssr: false }) as any,
  lorem: dynamic(() => import('@/app/components/tools/LoremTool'), { ssr: false }) as any,
  diff: dynamic(() => import('@/app/components/tools/DiffTool'), { ssr: false }) as any,
  jsonFormat: dynamic(() => import('@/app/components/tools/JsonFormatTool'), { ssr: false }) as any,
  xmlFormat: dynamic(() => import('@/app/components/tools/XmlFormatTool'), { ssr: false }) as any,
  sqlFormat: dynamic(() => import('@/app/components/tools/SqlFormatTool'), { ssr: false }) as any,
  colorConvert: dynamic(() => import('@/app/components/tools/ColorConvertTool'), { ssr: false }) as any,
  yamlToJson: dynamic(() => import('@/app/components/tools/YamlToJsonTool'), { ssr: false }) as any,
  csvToJson: dynamic(() => import('@/app/components/tools/CsvToJsonTool'), { ssr: false }) as any,
  urlEncode: dynamic(() => import('@/app/components/tools/UrlEncodeTool'), { ssr: false }) as any,
  base64Text: dynamic(() => import('@/app/components/tools/Base64TextTool'), { ssr: false }) as any,
  md5: dynamic(() => import('@/app/components/tools/Md5Tool'), { ssr: false }) as any,
  sha: dynamic(() => import('@/app/components/tools/ShaTool'), { ssr: false }) as any,
  uuid: dynamic(() => import('@/app/components/tools/UuidTool'), { ssr: false }) as any,
  password: dynamic(() => import('@/app/components/tools/PasswordTool'), { ssr: false }) as any,
  emailValidate: dynamic(() => import('@/app/components/tools/EmailValidateTool'), { ssr: false }) as any,
  regexTest: dynamic(() => import('@/app/components/tools/RegexTestTool'), { ssr: false }) as any,
  regexVisual: dynamic(() => import('@/app/components/tools/RegexVisualTool'), { ssr: false }) as any,
  jsonVisual: dynamic(() => import('@/app/components/tools/JsonVisualTool'), { ssr: false }) as any,
  colorPicker: dynamic(() => import('@/app/components/tools/ColorPickerTool'), { ssr: false }) as any,
  gradient: dynamic(() => import('@/app/components/tools/GradientTool'), { ssr: false }) as any,
  shadow: dynamic(() => import('@/app/components/tools/ShadowTool'), { ssr: false }) as any,
  flexbox: dynamic(() => import('@/app/components/tools/FlexboxTool'), { ssr: false }) as any,
  gridLayout: dynamic(() => import('@/app/components/tools/GridLayoutTool'), { ssr: false }) as any,
  gridGenerator: dynamic(() => import('@/app/components/tools/GridGeneratorTool'), { ssr: false }) as any,
  cssVariable: dynamic(() => import('@/app/components/tools/CssVariableTool'), { ssr: false }) as any,
  responsiveTest: dynamic(() => import('@/app/components/tools/ResponsiveTestTool'), { ssr: false }) as any,
  contrastCheck: dynamic(() => import('@/app/components/tools/ContrastCheckTool'), { ssr: false }) as any,
  radix: dynamic(() => import('@/app/components/tools/RadixTool'), { ssr: false }) as any,
  timestamp: dynamic(() => import('@/app/components/tools/TimestampTool'), { ssr: false }) as any,
  unitConvert: dynamic(() => import('@/app/components/tools/UnitConvertTool'), { ssr: false }) as any,
  dateCalc: dynamic(() => import('@/app/components/tools/DateCalcTool'), { ssr: false }) as any,
  mimeQuery: dynamic(() => import('@/app/components/tools/MimeQueryTool'), { ssr: false }) as any,
  calculator: dynamic(() => import('@/app/components/tools/CalculatorTool'), { ssr: false }) as any,
  qrcode: dynamic(() => import('@/app/components/tools/QRCodeTool'), { ssr: false }) as any,
  barcode: dynamic(() => import('@/app/components/tools/BarcodeTool'), { ssr: false }) as any,
  passwordStrength: dynamic(() => import('@/app/components/tools/PasswordStrengthTool'), { ssr: false }) as any,
  notepad: dynamic(() => import('@/app/components/tools/NotepadTool'), { ssr: false }) as any,
  pomodoro: dynamic(() => import('@/app/components/tools/PomodoroTool'), { ssr: false }) as any,
  scientificCalc: dynamic(() => import('@/app/components/tools/ScientificCalcTool'), { ssr: false }) as any,
  stickyNote: dynamic(() => import('@/app/components/tools/StickyNoteTool'), { ssr: false }) as any,
  countdown: dynamic(() => import('@/app/components/tools/CountdownTool'), { ssr: false }) as any,
  stopwatch: dynamic(() => import('@/app/components/tools/StopwatchTool'), { ssr: false }) as any,
  worldClock: dynamic(() => import('@/app/components/tools/WorldClockTool'), { ssr: false }) as any,
   timezone: dynamic(() => import('@/app/components/tools/TimezoneTool'), { ssr: false }) as any,
  randomNum: dynamic(() => import('@/app/components/tools/RandomNumTool'), { ssr: false }) as any,
  radixCalc: dynamic(() => import('@/app/components/tools/RadixCalcTool'), { ssr: false }) as any,
  csvEditor: dynamic(() => import('@/app/components/tools/CsvEditorTool'), { ssr: false }) as any,
  jsonEditor: dynamic(() => import('@/app/components/tools/JsonEditorTool'), { ssr: false }) as any,
  chart: dynamic(() => import('@/app/components/tools/ChartTool'), { ssr: false }) as any,
  statistics: dynamic(() => import('@/app/components/tools/StatisticsTool'), { ssr: false }) as any,
  pdfMerge: dynamic(() => import('@/app/components/tools/PdfMergeTool'), { ssr: false }) as any,
  pdfSplit: dynamic(() => import('@/app/components/tools/PdfSplitTool'), { ssr: false }) as any,
  pdfCompress: dynamic(() => import('@/app/components/tools/PdfCompressTool'), { ssr: false }) as any,
  pdfToImage: dynamic(() => import('@/app/components/tools/PdfToImageTool'), { ssr: false }) as any,
  pdfRotate: dynamic(() => import('@/app/components/tools/PdfRotateTool'), { ssr: false }) as any,
  pdfOrganize: dynamic(() => import('@/app/components/tools/PdfOrganizeTool'), { ssr: false }) as any,
  pdfWatermark: dynamic(() => import('@/app/components/tools/PdfWatermarkTool'), { ssr: false }) as any,
  pdfPageNumber: dynamic(() => import('@/app/components/tools/PdfPageNumberTool'), { ssr: false }) as any,
};

type Props = {
  slug: string;
  children?: React.ReactNode;
};

export default function ToolLoader({ slug, children }: Props) {
  const ToolComponent = toolComponents[slug];

  if (ToolComponent) {
    return React.createElement(ToolComponent, null, children);
  }

  return null;
}